name: Elixir CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18'
        otp-version: '25'
        install-hex: true
        install-rebar: true
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test --cover
